### ISSUE TITLE
Slack bericht formatting vanuit Berend verbeteren

### ISSUE THREAD

**Issue by delneet** [delneet/berend#2]
In #errors en #notifications staan berichten opgemaakt met blokken.
Misschien is het overzichtelijk om github events op die manier te formatteren.

**Comment by delneet** [comment]
https://api.slack.com/docs/message-guidelines

**Comment by wesleydebruijn** [comment]
Hier een voorbeeld:
[Formatted Pull Request assignment](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22color%22%3A%22%2336a64f%22%2C%22pretext%22%3A%22Wil%20je%20hier%20naar%20kijken%20%40peter%3F%22%2C%22author_name%22%3A%22websend%2Fmother%22%2C%22title%22%3A%22%5BMOB-3805%5D%20Retrieve%20providers%20from%20Postpaid%22%2C%22title_link%22%3A%22https%3A%2F%2Fgithub.com%2Fwebsend%2Fmother%2Fpull%2F3881%22%2C%22text%22%3A%22Pull%20Request%20van%20Wesley%20de%20Bruijn%22%7D%5D%7D)
